version: '3.6'

services:
  shellcheck:
    container_name: shellcheck
    build:
      context: docker/shellcheck
      dockerfile: Dockerfile
    image: crucible/shellcheck:1.0
    volumes:
      - ./src/:/srv/crucible
      - ./test/:/srv/crucible-test
      - ./.sh:/srv/.sh
  
  crucible:
    container_name: crucible
    build:
      context: docker/crucible
      dockerfile: Dockerfile
    image: crucible/bash:1.0
    volumes:
      - ./src:/srv/src
      - ./src/bash/bin/crucible:/bin/crucible
      - ./.sh:/srv/.sh
  
  crucible-test:
    container_name: crucible_test
    build:
      context: docker/crucible
      dockerfile: Dockerfile.test
    image: crucible/bash_test:1.0
    volumes:
      - ./test:/srv/test
      - ./src:/srv/src
      - ./src/bash/bin/crucible:/bin/crucible