FROM debian:buster-slim

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install --no-install-recommends -y wget=1.20.1-1.1 && \
    apt-get clean && \ 
    rm -rf /var/lib/apt/lists/*

RUN echo '#!/usr/bin/env bash\n\
for f in $(ls /srv/test/bash/**/*)\n\
do\n\
if [ -f $f ]; then bash $f; fi\n\
done\n\
' >> /var/run/startup.sh


CMD ["/usr/bin/env", "bash", "/var/run/startup.sh"]